name: Suggestion Report
description: File a suggestion report
title: "[Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your input, your suggestions are very useful to us!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Suggestion
    attributes:
      label: Suggestion
      description: Also tell us, why do you want to see this?
      placeholder: Tell us what you see!
      value: "My suggestion for an enhancement is..."
    validations:
      required: true
